# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER') %}
{% set build_string = "master_" + ((build_flavour + "_") if build_flavour else "") + build_number %}

package:
  name: gmpxxyy
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ build_string }}
  # cppyy is not available on Windows yet
  skip: True  # [win]
requirements:
  build:
    - libtool
    - automake
  host:
    - gmp
    # We pin to an explicit version of Python here; since the Python part is
    # noarch:python, the version does not matter. However, we need the same
    # version when doing "make install" so that files go into the site-packages
    # directory that was determined by ./configure.
    - python 3.7.*
    # enable test/pyexactreal tests in ./configure
    - pytest
    - cppyy
    # enable check-valgrind in ./configure
    - valgrind >=3.15.0
    # to run optional SageMath tests
    - sagelib
    - pip
    - ipywidgets
    - sympy

{%- if build_flavour %}
features:
  - {{ build_flavour }}
{% endif %}

{%- if not build_flavour %}
test:
  imports:
    - gmpxxyy
{% endif %}

about:
  home: https://github.com/flatsurf/gmpxxyy
  license: GPL2
  license_file: COPYING
  summary: A cppyy wrapper for GMP

extra:
  recipe-maintainers:
    - saraedum
