# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set target = target or 'release' %}
{% set name = 'gmpxxyy' if target == 'release' else 'gmppxxyy-ci' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ target }}_py{{ python }}_{{ build_number }}
  # cppyy is not available on Windows yet
  skip: True  # [win]
  # we do not support old versions of Python
  skip: True  # [py<36]
{%- if target not in ["test", "release"] %}
  # ignore Python version where it does not matter (conda-smithy still renders these but conda-build stops immediately)
  skip: True  # [py != 37]
  # ignore OS where it does not matter (conda-smithy still renders these but conda-build stops immediately)
  skip: True  # [not linux]
{%- endif %}
  run_exports:
    - gmpxxyy {{ version }}

requirements:
  build:
    - libtool
    - automake
  host:
    - python
{%- if target in ["test"] %}
    # enable pytest in ./configure
    - pytest
    - cppyy
    - cppyythonizations
    # enable check-valgrind in ./configure
    - valgrind >=3.15.0  # [linux]
    # to run optional SageMath tests
    - sagelib
    - pip
    - ipywidgets
    - sympy
{%- endif %}
  run:
    - cppyy
    - cppyythonizations
    - python

outputs:
  - name:  {{ name }}
{%- if target == 'release' %}
    script: install.sh
    test:
      imports:
        - gmpxxyy
{% endif %}


about:
  home: https://github.com/flatsurf/gmpxxyy
  license: GPL2
  license_file: COPYING
  summary: A cppyy wrapper for GMP

extra:
  recipe-maintainers:
    - saraedum
