{% set version = '1.0.0' %}
{% set build_number = '0' %}

package:
  name: gmpxxyy
  version: {{ version }}

source:
  path: ../

build:
  number: {{ build_number }}
  # cppyy is not available on Windows yet
  skip: True  # [win]
  # cppyy on macOS does not support C++17 without explicit switches currently; https://github.com/conda-forge/cppyy-feedstock/issues/21
  skip: True  # [osx]
  run_exports:
    - gmpxxyy {{ version }}

requirements:
  build:
    - libtool
    - automake
  host:
    - python
    - setuptools
    - gmp {{ gmp }}
  run:
    - cppyy
    - cppyythonizations
    - python

test:
  imports:
    - gmpxxyy

about:
  home: https://github.com/flatsurf/gmpxxyy
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: A cppyy wrapper for GMP
