# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set build_string = "master_" + ((build_flavour + "_") if build_flavour else "") + build_number %}

package:
  name: gmpxxyy
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ build_string }}
  # cppyy is not available on Windows yet
  skip: True  # [win]
  skip: True  # [py<36]
{%- if build_flavour %}
  # only run non-release checks on Linux/3.7 (unfortunately, the py selector is ignored.)
  skip: True  # [not linux or py<37]
{% endif %}
  run_exports:
    - gmpxxyy {{ version }}

requirements:
  build:
    - libtool
    - automake
  host:
    - python
    - gmp
    # enable pytest in ./configure
    - pytest
    - cppyy
    # enable check-valgrind in ./configure
    - valgrind >=3.15.0  # [linux]
    # to run optional SageMath tests
    - sagelib
    - pip
    - ipywidgets
    - sympy
  run:
    - cppyy
    - python

{%- if build_flavour %}
features:
  - {{ build_flavour }}
{% endif %}

{%- if not build_flavour %}
test:
  imports:
    - gmpxxyy
{% endif %}

about:
  home: https://github.com/flatsurf/gmpxxyy
  license: GPL2
  license_file: COPYING
  summary: A cppyy wrapper for GMP

extra:
  recipe-maintainers:
    - saraedum
